export const categoryData = {
    Medicals: [
        'Doctor',
        'Nurse',
        'Dietitian',
        'Surgeon',
        'Physician',
        'Pharmacist',
        'Radiologist',
        'Pediatrician',
        'Psychologist',
        'Physical Therapist',
        'Dentist',
        'Lab Technician',
        'Chiropractor',
        'Anesthesiologist',
        'Cardiologist',
        'Dermatologist',
        'Gynecologist',
        'Neurosurgeon',
    ],
    HandyMan: [
        'Plumber',
        'Electrician',
        'Mechanic',
        'Carpenter',
        'Painter',
        'HVAC Technician',
        'Welder',
        'Roofer',
        'Mason',
        'Landscaper',
        'General Contractor',
        'Locksmith',
        'Glazier',
        'Handyman',
        'Tiler',
        'Flooring Installer',
    ],
    Education: [
        'Teacher',
        'Tutor',
        'Counselor',
        'Professor',
        'Librarian',
        'Teaching Assistant',
        'Curriculum Developer',
        'Special Education Teacher',
        'Instructional Designer',
        'Academic Advisor',
        'Language Instructor',
        'Researcher',
        'School Administrator',
        'Art Teacher',
        'Music Teacher',
        'Physical Education Instructor',
    ],
    Transportation: [
        'Driver',
        'Courier',
        'Logistics Coordinator',
        'Truck Driver',
        'Bus Driver',
        'Delivery Driver',
        'Taxi Driver',
        'Chauffeur',
        'Fleet Manager',
        'Dispatcher',
        'Forklift Operator',
        'Freight Broker',
        'Marine Engineer',
        'Pilot',
        'Train Conductor',
        'Warehouse Manager',
    ],
};
