import usman from "../../assets/images/usman.png"
const Orders = [
    {
        image:usman,
        subject: 'Health Issues',
        name: "Daniel Gabriel",
        date: "Monday, 5th January - 11:50pm",
        amount: "₦5,500",
        status: "Active",
        color: 'rgba(178, 214, 255, 1)',
    },
    {
        image:usman,
        subject: 'Medication',
        name: "Micheal Moses",
        date: "Tuesday, 6th January - 7:50pm",
        amount: "₦9,000",
        status: "Done",
        color: "green",
    },
    {
        image:usman,
        name: "Mike Dan",
        subject: 'Therapist Section',
        date: "Thursday, 8th January - 10:30am",
        amount: "₦5,500",
        status: "Canceled",
        color: 'rgba(255, 178, 178, 1)',
    },
    {
        image:usman,
        name: "Goerge Jack",
        subject: 'Treatment',
        date: "Friday, 9th January - 1:30am",
        amount: "₦15,000",
        status: "Pending",
        color: 'rgba(255, 242, 178, 1)',
    },
    {
        image:usman,
        name: "Tobi Forge",
        subject: 'Therapist Section',
        date: "Monday, 13th January - 12:50pm",
        amount: "₦17,500",
        status: "Active",
        color: 'rgba(178, 214, 255, 1)',
    },
    {
        image:usman,
        name: "Moses Mike",
        subject: 'Medication',
        date: "Tuesday, 14th January - 7:50am",
        amount: "₦20,000",
        status: "Done",
        color: "green",
    },
    {
        image:usman,
        name: "Dan Dan",
        subject: 'Treatment',
        date: "Thursday, 15th January - 10:30am",
        amount: "₦35,000",
        status: "Canceled",
        color: 'rgba(255, 178, 178, 1)',
    },
    {
        image:usman,
        name: "Joseph Yisa",
        subject: 'Medication',
        date: "Friday, 9th January - 1:30am",
        amount: "₦15,000",
        status: "Pending",
        color: 'rgba(255, 242, 178, 1)',
    },
]

export default Orders;